version: "3.8"

services:
  # NestJS Backend API (с базой данных внутри)
  backend:
    image: mip92/tattoo-server:latest
    container_name: tattoo-backend-prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      # Database Configuration
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: ${DATABASE_URL}
      # Server Configuration
      PORT: ${SERVER_PORT}
      # JWT Configuration
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TOKEN_EXPIRES_IN: ${JWT_ACCESS_TOKEN_EXPIRES_IN:-15m}
      JWT_REFRESH_TOKEN_EXPIRES_IN: ${JWT_REFRESH_TOKEN_EXPIRES_IN:-7d}
      NODE_OPTIONS: "--max-old-space-size=256"
    volumes:
      - backend_data:/app/data # Volume для сохранения данных базы
    networks:
      - tattoo-network
    ports:
      - "3000:3000" # Порт для API
    command: npm run start:prod
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Next.js Frontend
  frontend:
    image: mip92/tattoo-client:latest
    container_name: tattoo-frontend-prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://backend:3000}
      NODE_OPTIONS: "--max-old-space-size=128"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - tattoo-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: tattoo-nginx-prod
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-local.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - backend
      - frontend
    networks:
      - tattoo-network

networks:
  tattoo-network:
    driver: bridge

volumes:
  backend_data: # Volume для сохранения данных базы внутри backend
