version: "3.8"

services:
  # База данных PostgreSQL
  database:
    image: postgres:15-alpine
    container_name: tattoo-database-prod
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - tattoo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # NestJS Backend API
  backend:
    image: mip92/tattoo-server:latest
    container_name: tattoo-backend-prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TOKEN_EXPIRES_IN: ${JWT_ACCESS_TOKEN_EXPIRES_IN:-15m}
      JWT_REFRESH_TOKEN_EXPIRES_IN: ${JWT_REFRESH_TOKEN_EXPIRES_IN:-7d}
      PORT: 3000
      NODE_OPTIONS: "--max-old-space-size=256"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - tattoo-network
    command: npm run start:prod

  # Next.js Frontend (без Docker)
  frontend:
    image: node:22-alpine
    container_name: tattoo-frontend-prod
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://backend:3000}
      NODE_OPTIONS: "--max-old-space-size=128"
    depends_on:
      - backend
    networks:
      - tattoo-network
    command: sh -c "npm install && npm run start"

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: tattoo-nginx-prod
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-local.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - backend
      - frontend
    networks:
      - tattoo-network

volumes:
  postgres_data_prod:

networks:
  tattoo-network:
    driver: bridge
