version: "3.8"
services:
  database:
    image: postgres:alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: tattoo
      POSTGRES_PASSWORD: tattoo_pass
      POSTGRES_DB: tattoo_db
