name: 🚀 Deploy to DigitalOcean

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          port: 22
          script: |
            echo "🚀 Starting deployment..."
            cd ~/tattoo-app

            # Останавливаем текущее приложение
            echo "⏹️  Stopping current application..."
            docker-compose -f docker-compose.prod.yml down || true

            # Обновляем backend репозиторий
            echo "📥 Updating backend..."
            if [ -d "backend" ]; then
              cd backend
              git fetch origin
              git reset --hard origin/main
              cd ..
            else
              echo "❌ Backend directory not found"
              exit 1
            fi

            # Обновляем frontend репозиторий
            echo "📥 Updating frontend..."
            if [ -d "frontend" ]; then
              cd frontend
              git fetch origin
              git reset --hard origin/main
              cd ..
            else
              echo "❌ Frontend directory not found"
              exit 1
            fi

            # Пересобираем и запускаем
            echo "🔨 Rebuilding and starting application..."
            docker-compose -f docker-compose.prod.yml build --no-cache
            docker-compose -f docker-compose.prod.yml up -d

            # Проверяем статус
            echo "🔍 Checking application status..."
            docker-compose -f docker-compose.prod.yml ps

            echo "✅ Deployment completed successfully!"

      - name: 🔍 Health Check
        if: success()
        run: |
          echo "Waiting for application to start..."
          sleep 30

          # Проверяем доступность API
          if curl -f http://${{ secrets.DIGITALOCEAN_HOST }}/health; then
            echo "✅ API is healthy"
          else
            echo "❌ API health check failed"
            exit 1
          fi

          # Проверяем доступность фронтенда
          if curl -f http://${{ secrets.DIGITALOCEAN_HOST }}/; then
            echo "✅ Frontend is accessible"
          else
            echo "❌ Frontend check failed"
            exit 1
          fi
